name: CI-CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest

  deploy:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (simulasi pakai secret)
        env:
          DB_PASSWORD: ${{ secrets.FAKE_DB_PASSWORD }}
        run: echo "Deploying dengan koneksi DB (password ter-mask otomatis oleh GitHub)"